import Providers from '@/util/Providers'
import type { Metadata } from 'next'
import { Bitter } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const font = Bitter({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'TODO_BIRD',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${font.className} w-screen h-screen antialiased`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  )
}
